<%@ Page Title="Grid View with DetailView Control" Language="C#"
  MasterPageFile="~/MasterPages/Bootstrap.Master"
  AutoEventWireup="true"
  CodeBehind="GridViewSample03.aspx.cs"
  Inherits="FormsOverDataSamples.GridViewSample03" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
  <!-- Bring in Pager Styles -->
  <link href="../css/PagerStyle.css" rel="stylesheet" type="text/css" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
  <h3>Grid View and Detail View Controls</h3>
  <form id="form1" runat="server">
    <div class="table-responsive">
      <asp:DetailsView ID="vwProduct" runat="server"
        CssClass="table table-striped table-bordered"
        AutoGenerateEditButton="true"
        AutoGenerateInsertButton="true"
        AutoGenerateDeleteButton="true"
        DataSourceID="odsAProduct">
      </asp:DetailsView>
    </div>
    <div class="table-responsive">
      <asp:GridView ID="grdProducts" runat="server"
        DataSourceID="odsProducts"
        CssClass="table table-striped table-bordered"
        PageSize="4"
        AllowPaging="True"
        DataKeyNames="ProductId">
        <Columns>
          <asp:CommandField ShowSelectButton="True" />
        </Columns>
      </asp:GridView>
    </div>
  </form>
  <asp:ObjectDataSource ID="odsProducts" runat="server"
    TypeName="FormsOverDataSamples.ProductManager"
    SelectMethod="GetProducts" />
  <asp:ObjectDataSource ID="odsAProduct"
    runat="server"
    TypeName="FormsOverDataSamples.ProductManager"
    SelectMethod="GetProduct">
    <SelectParameters>
      <asp:ControlParameter ControlID="grdProducts"
        Name="productId"
        PropertyName="SelectedValue"
        Type="Int32" />
    </SelectParameters>
  </asp:ObjectDataSource>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="EndOfPageContent" runat="server">
  <script>
    // Make DetailView 'Edit', 'Delete', 'New' links show as buttons
    $(document).ready(function () {
      $("td[colspan='2'] a").addClass('btn btn-primary');
    });
  </script>
</asp:Content>
